

export const ACTION_TYPES = {

    AUTH_LOGIN : "AUTH_LOGIN",
    AUTH_LOGOUT : "AUTH_LOGOUT",

    TODO_ADD : "TODO_ADD",
    TODO_REMOVE : "TODO_REMOVE",
    TODO_COMPLETE : "TODO_COMPLETE",
    TODO_UNDOCOMPLETE : "TODO_UNDOCOMPLETE"


}