// flow-typed signature: 5e4a0081d464d434081cef7cb32d1172
// flow-typed version: <<STUB>>/bootstrap-vue_v^1.0.0-beta.9/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap-vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap-vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap-vue/dist/bootstrap-vue.common' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/dist/bootstrap-vue.common.min' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/dist/bootstrap-vue.esm' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/dist/bootstrap-vue.esm.min' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/dist/bootstrap-vue' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/dist/bootstrap-vue.min' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/classes/BvEvent' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/classes/index' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/classes/popover' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/classes/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/classes/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components-extra/index' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/badge' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/breadcrumb-item' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/breadcrumb-link' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/breadcrumb' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/button-close' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/button-group' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/button' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/card-body' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/card-footer' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/card-group' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/card-header' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/card-img' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/card' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/col' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/container' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/dropdown-divider' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/dropdown-header' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/dropdown-item-button' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/dropdown-item' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/embed' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/form-feedback' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/form-row' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/form-text' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/form' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/img' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/index' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/input-group-addon' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/input-group-button' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/jumbotron' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/link' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/list-group-item' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/list-group' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/media-aside' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/media-body' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/media' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/nav-form' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/nav-item' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/nav-text' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/nav' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/navbar-brand' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/navbar' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/components/row' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/directives-extra/index' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/directives-extra/test' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/directives/_target' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/directives/index' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/directives/modal' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/directives/popover' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/directives/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/directives/toggle' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/directives/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/index' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/card-mixin' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/clickout' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/dropdown' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/form-custom' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/form-options' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/form-radio-check' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/form-size' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/form-state' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/form' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/id' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/index' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/listen-on-root' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/pagination' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/mixins/toolpop' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/addEventListenerOnce' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/array' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/copyProps' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/dom' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/identity' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/index' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/loose-equal' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/lowerFirst' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/memoize' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/object' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/observe-dom' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/pluckProps' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/prefixPropName' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/range' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/suffixPropName' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/unPrefixPropName' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/upperFirst' {
  declare module.exports: any;
}

declare module 'bootstrap-vue/lib/utils/warn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap-vue/dist/bootstrap-vue.common.js' {
  declare module.exports: $Exports<'bootstrap-vue/dist/bootstrap-vue.common'>;
}
declare module 'bootstrap-vue/dist/bootstrap-vue.common.min.js' {
  declare module.exports: $Exports<'bootstrap-vue/dist/bootstrap-vue.common.min'>;
}
declare module 'bootstrap-vue/dist/bootstrap-vue.esm.js' {
  declare module.exports: $Exports<'bootstrap-vue/dist/bootstrap-vue.esm'>;
}
declare module 'bootstrap-vue/dist/bootstrap-vue.esm.min.js' {
  declare module.exports: $Exports<'bootstrap-vue/dist/bootstrap-vue.esm.min'>;
}
declare module 'bootstrap-vue/dist/bootstrap-vue.js' {
  declare module.exports: $Exports<'bootstrap-vue/dist/bootstrap-vue'>;
}
declare module 'bootstrap-vue/dist/bootstrap-vue.min.js' {
  declare module.exports: $Exports<'bootstrap-vue/dist/bootstrap-vue.min'>;
}
declare module 'bootstrap-vue/lib/classes/BvEvent.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/classes/BvEvent'>;
}
declare module 'bootstrap-vue/lib/classes/index.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/classes/index'>;
}
declare module 'bootstrap-vue/lib/classes/popover.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/classes/popover'>;
}
declare module 'bootstrap-vue/lib/classes/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/classes/scrollspy'>;
}
declare module 'bootstrap-vue/lib/classes/tooltip.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/classes/tooltip'>;
}
declare module 'bootstrap-vue/lib/components-extra/index.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components-extra/index'>;
}
declare module 'bootstrap-vue/lib/components/badge.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/badge'>;
}
declare module 'bootstrap-vue/lib/components/breadcrumb-item.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/breadcrumb-item'>;
}
declare module 'bootstrap-vue/lib/components/breadcrumb-link.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/breadcrumb-link'>;
}
declare module 'bootstrap-vue/lib/components/breadcrumb.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/breadcrumb'>;
}
declare module 'bootstrap-vue/lib/components/button-close.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/button-close'>;
}
declare module 'bootstrap-vue/lib/components/button-group.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/button-group'>;
}
declare module 'bootstrap-vue/lib/components/button.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/button'>;
}
declare module 'bootstrap-vue/lib/components/card-body.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/card-body'>;
}
declare module 'bootstrap-vue/lib/components/card-footer.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/card-footer'>;
}
declare module 'bootstrap-vue/lib/components/card-group.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/card-group'>;
}
declare module 'bootstrap-vue/lib/components/card-header.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/card-header'>;
}
declare module 'bootstrap-vue/lib/components/card-img.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/card-img'>;
}
declare module 'bootstrap-vue/lib/components/card.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/card'>;
}
declare module 'bootstrap-vue/lib/components/col.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/col'>;
}
declare module 'bootstrap-vue/lib/components/container.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/container'>;
}
declare module 'bootstrap-vue/lib/components/dropdown-divider.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/dropdown-divider'>;
}
declare module 'bootstrap-vue/lib/components/dropdown-header.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/dropdown-header'>;
}
declare module 'bootstrap-vue/lib/components/dropdown-item-button.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/dropdown-item-button'>;
}
declare module 'bootstrap-vue/lib/components/dropdown-item.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/dropdown-item'>;
}
declare module 'bootstrap-vue/lib/components/embed.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/embed'>;
}
declare module 'bootstrap-vue/lib/components/form-feedback.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/form-feedback'>;
}
declare module 'bootstrap-vue/lib/components/form-row.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/form-row'>;
}
declare module 'bootstrap-vue/lib/components/form-text.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/form-text'>;
}
declare module 'bootstrap-vue/lib/components/form.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/form'>;
}
declare module 'bootstrap-vue/lib/components/img.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/img'>;
}
declare module 'bootstrap-vue/lib/components/index.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/index'>;
}
declare module 'bootstrap-vue/lib/components/input-group-addon.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/input-group-addon'>;
}
declare module 'bootstrap-vue/lib/components/input-group-button.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/input-group-button'>;
}
declare module 'bootstrap-vue/lib/components/jumbotron.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/jumbotron'>;
}
declare module 'bootstrap-vue/lib/components/link.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/link'>;
}
declare module 'bootstrap-vue/lib/components/list-group-item.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/list-group-item'>;
}
declare module 'bootstrap-vue/lib/components/list-group.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/list-group'>;
}
declare module 'bootstrap-vue/lib/components/media-aside.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/media-aside'>;
}
declare module 'bootstrap-vue/lib/components/media-body.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/media-body'>;
}
declare module 'bootstrap-vue/lib/components/media.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/media'>;
}
declare module 'bootstrap-vue/lib/components/nav-form.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/nav-form'>;
}
declare module 'bootstrap-vue/lib/components/nav-item.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/nav-item'>;
}
declare module 'bootstrap-vue/lib/components/nav-text.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/nav-text'>;
}
declare module 'bootstrap-vue/lib/components/nav.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/nav'>;
}
declare module 'bootstrap-vue/lib/components/navbar-brand.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/navbar-brand'>;
}
declare module 'bootstrap-vue/lib/components/navbar.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/navbar'>;
}
declare module 'bootstrap-vue/lib/components/row.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/components/row'>;
}
declare module 'bootstrap-vue/lib/directives-extra/index.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/directives-extra/index'>;
}
declare module 'bootstrap-vue/lib/directives-extra/test.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/directives-extra/test'>;
}
declare module 'bootstrap-vue/lib/directives/_target.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/directives/_target'>;
}
declare module 'bootstrap-vue/lib/directives/index.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/directives/index'>;
}
declare module 'bootstrap-vue/lib/directives/modal.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/directives/modal'>;
}
declare module 'bootstrap-vue/lib/directives/popover.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/directives/popover'>;
}
declare module 'bootstrap-vue/lib/directives/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/directives/scrollspy'>;
}
declare module 'bootstrap-vue/lib/directives/toggle.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/directives/toggle'>;
}
declare module 'bootstrap-vue/lib/directives/tooltip.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/directives/tooltip'>;
}
declare module 'bootstrap-vue/lib/index.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/index'>;
}
declare module 'bootstrap-vue/lib/mixins/card-mixin.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/card-mixin'>;
}
declare module 'bootstrap-vue/lib/mixins/clickout.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/clickout'>;
}
declare module 'bootstrap-vue/lib/mixins/dropdown.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/dropdown'>;
}
declare module 'bootstrap-vue/lib/mixins/form-custom.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/form-custom'>;
}
declare module 'bootstrap-vue/lib/mixins/form-options.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/form-options'>;
}
declare module 'bootstrap-vue/lib/mixins/form-radio-check.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/form-radio-check'>;
}
declare module 'bootstrap-vue/lib/mixins/form-size.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/form-size'>;
}
declare module 'bootstrap-vue/lib/mixins/form-state.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/form-state'>;
}
declare module 'bootstrap-vue/lib/mixins/form.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/form'>;
}
declare module 'bootstrap-vue/lib/mixins/id.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/id'>;
}
declare module 'bootstrap-vue/lib/mixins/index.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/index'>;
}
declare module 'bootstrap-vue/lib/mixins/listen-on-root.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/listen-on-root'>;
}
declare module 'bootstrap-vue/lib/mixins/pagination.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/pagination'>;
}
declare module 'bootstrap-vue/lib/mixins/toolpop.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/mixins/toolpop'>;
}
declare module 'bootstrap-vue/lib/utils/addEventListenerOnce.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/addEventListenerOnce'>;
}
declare module 'bootstrap-vue/lib/utils/array.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/array'>;
}
declare module 'bootstrap-vue/lib/utils/copyProps.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/copyProps'>;
}
declare module 'bootstrap-vue/lib/utils/dom.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/dom'>;
}
declare module 'bootstrap-vue/lib/utils/identity.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/identity'>;
}
declare module 'bootstrap-vue/lib/utils/index.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/index'>;
}
declare module 'bootstrap-vue/lib/utils/loose-equal.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/loose-equal'>;
}
declare module 'bootstrap-vue/lib/utils/lowerFirst.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/lowerFirst'>;
}
declare module 'bootstrap-vue/lib/utils/memoize.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/memoize'>;
}
declare module 'bootstrap-vue/lib/utils/object.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/object'>;
}
declare module 'bootstrap-vue/lib/utils/observe-dom.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/observe-dom'>;
}
declare module 'bootstrap-vue/lib/utils/pluckProps.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/pluckProps'>;
}
declare module 'bootstrap-vue/lib/utils/prefixPropName.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/prefixPropName'>;
}
declare module 'bootstrap-vue/lib/utils/range.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/range'>;
}
declare module 'bootstrap-vue/lib/utils/suffixPropName.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/suffixPropName'>;
}
declare module 'bootstrap-vue/lib/utils/unPrefixPropName.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/unPrefixPropName'>;
}
declare module 'bootstrap-vue/lib/utils/upperFirst.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/upperFirst'>;
}
declare module 'bootstrap-vue/lib/utils/warn.js' {
  declare module.exports: $Exports<'bootstrap-vue/lib/utils/warn'>;
}
