// flow-typed signature: 463f8bc3f797f82a081889a79205b225
// flow-typed version: <<STUB>>/es6-promise-promise_v^1.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-promise-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-promise-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'es6-promise-promise/index' {
  declare module.exports: $Exports<'es6-promise-promise'>;
}
declare module 'es6-promise-promise/index.js' {
  declare module.exports: $Exports<'es6-promise-promise'>;
}
