// flow-typed signature: d63854780d6aa9929566f54e59df7055
// flow-typed version: <<STUB>>/phantomjs-prebuilt_v^2.1.14/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'phantomjs-prebuilt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'phantomjs-prebuilt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'phantomjs-prebuilt/install' {
  declare module.exports: any;
}

declare module 'phantomjs-prebuilt/lib/location' {
  declare module.exports: any;
}

declare module 'phantomjs-prebuilt/lib/phantomjs' {
  declare module.exports: any;
}

declare module 'phantomjs-prebuilt/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'phantomjs-prebuilt/install.js' {
  declare module.exports: $Exports<'phantomjs-prebuilt/install'>;
}
declare module 'phantomjs-prebuilt/lib/location.js' {
  declare module.exports: $Exports<'phantomjs-prebuilt/lib/location'>;
}
declare module 'phantomjs-prebuilt/lib/phantomjs.js' {
  declare module.exports: $Exports<'phantomjs-prebuilt/lib/phantomjs'>;
}
declare module 'phantomjs-prebuilt/lib/util.js' {
  declare module.exports: $Exports<'phantomjs-prebuilt/lib/util'>;
}
